package org.concordion.internal.listener;

import org.concordion.api.Element;
import org.concordion.api.Resource;
import org.concordion.api.Target;
import org.concordion.api.listener.SpecificationProcessingEvent;
import org.concordion.api.listener.SpecificationProcessingListener;
import org.concordion.internal.util.Check;

public class PageFooterRenderer implements SpecificationProcessingListener {

    private static final String CONCORDION_WEBSITE_URL = "http://www.concordion.org";
    private long startMillis;

    public PageFooterRenderer(Target target) {
    }

    public void beforeProcessingSpecification(SpecificationProcessingEvent event) {
        startMillis = System.currentTimeMillis();
    }

    public void afterProcessingSpecification(SpecificationProcessingEvent event) {
        try {
            long millisTaken = System.currentTimeMillis() - startMillis;
            addFooterToDocument(event.getRootElement(), event.getResource(), millisTaken);
        } catch (Throwable t) {
            t.printStackTrace();
            Check.isTrue(false, "Failed to write page footer. " + t.getMessage());
        }
    }

    private void addFooterToDocument(Element rootElement, Resource resource, long millisTaken) {
        Element body = rootElement.getFirstChildElement("body");
        
        if (body != null) {
            
            Element footer = new Element("div");
            footer.addStyleClass("footer");
            footer.appendText("Results generated by ");
            
            Element link = new Element("a");
            link.addAttribute("href", CONCORDION_WEBSITE_URL);
            link.addAttribute("style", "font-weight: bold; text-decoration: none; color: #89C;");
            footer.appendChild(link);
            link.appendText("Concordion");
            
            body.appendChild(footer);
        }
    }
}
